# Site settings
title: Kevin Deng
email: kaijendeng2016@u.northwestern.edu
url: https://kdeng2016.github.io
description: "Kevin Deng Data Science Blog"
skills: "Data Science & Business Intelligence"
meta_author: Kevin Deng

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: kdeng

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9a2424 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 691414 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright1: Dr. Henry Jekyll
  copyright2: Kevin Deng
  location: Location
  social: Connect
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kjdeng
  - title: envelope-o
    url: kaijendeng2016@u.northwestern.edu
  - title: github
    url: https://github.com/kdeng2016
  # - title: file-pdf-o
  #   url: file/resume.pdf

# Postal address (add as many lines as necessary)
address: 
  - line: 
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
